#!/bin/bash

#####################################
# Este script instala o Julia pré-compilado com
# alguns pacotes utilizados nas disciplinas de otimização.
#
# Testado no GNU/Linux Ubuntu 22.04. Para rodar este script, execute
#   sh instalar_julia
# do terminal, da pasta em que salvou o script.
#
# Autor: Leonardo D. Secchin, 24/06/23
#####################################

echo "======================================================"
echo "Recomenda-se instalar a última versão ESTÀVEL do Julia"
echo "Para saber qual a versão atual, consulte"
echo "   https://julialang.org/downloads/"
echo "e veja a versão em 'Current stable release'"
echo "======================================================"

echo
echo "Digite a versão no formato X.X.X (sem o 'v'): "

read VERSAO
if [ -z $VERSAO ]; then
    echo "Versão inválida!"
    exit 1
fi

echo
echo "Baixando versão $VERSAO no diretório do usuário..."
echo

# vai para o diretório home do usuário
cd ~

rm -f julia-$VERSAO-linux-x86_64.tar.gz*
# baixa o Julia pré-compilado
if ! wget https://julialang-s3.julialang.org/bin/linux/x64/${VERSAO:0:3}/julia-$VERSAO-linux-x86_64.tar.gz; then
    echo
    echo "URL não encontrada! Verifique se a versão existe. Caso afirmativo, você poderá ter que ajustar a URL no script."
    echo
    exit 1
fi

echo
echo "Descompactando Julia para a pasta 'julia-$VERSAO'..."
echo

# descompacta o Julia
tar -xf julia-$VERSAO-linux-x86_64.tar.gz


echo
echo "Adicionando atalho para o comando 'julia' via terminal do sistema (funcionará após reabrir o terminal)..."
echo

# cria comando "julia" para chamar Julia de qualquer lugar pelo terminal
echo "alias julia=""~/julia-$VERSAO/bin/./julia""" >> ~/.bashrc
source ~/.bashrc


echo
echo "Verificando pacotes de sistema (necessário senha do administrador)..."
echo

# instala pré-requisitos no sistema (requer senha do administrador)
sudo apt update
sudo apt install gfortran g++ gcc libopenblas-dev -y


echo
echo "======================================================="
echo "                   AVISO IMPORTANTE"
echo
echo "O Julia já está instalado em sua máquina!"
echo
echo "Na próxima etapa, pacotes serão instalados no Julia."
echo "Se esta etapa falhar, NÃO EXECUTE este script novamente"
echo "pois isso apagará sua instalação."
echo "Ao invés disso, entre no Julia e instale os pacotes que"
echo "precisa manualmente."
echo "======================================================="
echo

echo "Pressione qualquer tecla para continuar"
read

echo
echo "Instalando pacotes no Julia..."
echo

# instala pacotes no Julia
~/julia-$VERSAO/bin/./julia -e 'using Pkg;
Pkg.update();
Pkg.add("Metaheuristics");
Pkg.add("TSPLIB");
Pkg.add("Random");
Pkg.add("Distributions");
Pkg.add("Plots");'

echo
echo "Pacotes instalados!"
echo
